name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1024177687549/locations/global/workloadIdentityPools/github-actions-pool/providers/github
          service_account: github-deployer@shnare-dws-osiruo-2026.iam.gserviceaccount.com
          token_format: access_token

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and push frontend image
        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-sharing-repo/frontend:latest ./frontend
          docker push europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-sharing-repo/frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-sharing-repo/backend:latest ./backend
          docker push europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-sharing-repo/backend:latest

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy shnare-frontend \
            --image europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-sharing-repo/frontend:latest \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy shnare-backend \
            --image europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-sharing-repo/backend:latest \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated