name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1024177687549/locations/global/workloadIdentityPools/github-actions-pool/providers/github
          service_account: github-deployer@shnare-dws-osiruo-2026.iam.gserviceaccount.com

      - name: Deploy frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: frontend-service
          region: europe-west3
          source: ./frontend

      - name: Deploy backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: backend-service
          region: europe-west3
          source: ./backend